[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
TensorKitchen = "3630a16b-0f2f-4d88-afbf-c7d59eccf553"

[sources]
Manifolds = {url = "https://github.com/JuliaManifolds/Manifolds.jl.git", rev = "651492d7865f700d6b5db3673f8dbf6e366cc92f"}
TensorKitchen = {path = ".."}

[compat]
Documenter = "1"
Manifolds = "0.11.31"
